name: Generate Books Markdown

on:
  push:
    paths:
      - 'books/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run script
      run: python generate_books_md.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update books.md"
        title: "Update books.md"
        body: "Updates to books.md"
        branch: "updates/books-md"
